[package]
authors = ["Jakub Pastuszek <jpastuszek@gmail.com>"]
name = "micro_rts_rs"
version = "0.1.0"

[dependencies]
ansi_term = "0.9.0"
itertools = "0.6.0"
pathfinding = "0.1.13"

[lib]
name = "micro_rts"